name: drupal-gatsby-theme

services:
  storybook:
    type: node:12
    port: 6006
    build:
      - yarn
    command: yarn workspace gatsby-theme storybook

proxy:
  storybook:
    - drupal-gatsby-theme-sb.lndo.site:6006

tooling:
  npm:
    cmd: Nope, try `lando yarn` instead.
    service:
      - storybook
  node:
    service:
      - storybook
  yarn:
    service:
      - storybook
